### ISSUE TITLE
"TypeError: render is not a function" when running tests in a monorepo using Yarn 3.x and vitest

### ISSUE THREAD

**Issue by JakeYallop** [solidjs/solid-testing-library#30]
Repro repository here (basically a copy of my actual repository. with everything ripped out other than the bare minimum):
https://github.com/JakeYallop/SolidjsRepro

Trying to run a very basic unit test 
```tsx
//App.tsx
import type { Component } from "solid-js";

const App: Component = () => {
  return <>Test</>;
};

export default App;
```
```tsx
//App.test.tsx
import { describe, it, expect } from "vitest";
import { render } from "@solidjs/testing-library";
import App from "./App";

describe("App", () => {
  it("should render", () => {
    const { unmount, container } = render(() => <App />);
    expect(unmount).toBeTruthy();
    unmount();
  });
});
```
Produces:
```
TypeError: render is not a function
```
![image](https://user-images.githubusercontent.com/30874283/204623071-fddecb12-e909-479c-be29-998e4e4c6b6e.png)

What am I doing wrong?

**Comment by atk** [comment]
In vite config, instead of test.deps.inline..., use test.deps.registerNodeLoader: true.

**Comment by JakeYallop** [comment]
Tried doing the following (and pushed the changes up to the repro repo):

```diff
    test: {
-      deps: {
-       inline: [
-           //https://github.com/solidjs/solid-testing-library/issues/10
-           "@solidjs/testing-library",
-        ],
-      },
+      deps: {
+        registerNodeLoader: true,
+      },
      environment: "happy-dom",
      //https://vitest.dev/config/#transformmode
      transformMode: {
        web: [/\.[jt]sx$/],
      },
    },
```

With that change, I get the following error:

```
node:internal/event_target:1006
  process.nextTick(() => { throw err; });
                           ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\JakeYallop\source\repos\SolidjsTestingRepro\.yarn\__virtual__\vitest-virtual-e7e43f7ad2\0\cache\vitest-npm-0.25.3-4ee5af907c-cd54de758f.zip\node_modules\vitest\dist\loader.js' imported from C:\Users\JakeYallop\source\repos\SolidjsTestingRepro\playground\
Did you mean to import C:/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/__virtual__/vitest-virtual-e7e43f7ad2/0/cache/vitest-npm-0.25.3-4ee5af907c-cd54de758f.zip/node_modules/vitest/dist/loader.js?
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:323:11)
    at moduleResolve (node:internal/modules/esm/resolve:916:10)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:521:22)
    at initializeLoader (node:internal/process/esm_loader:75:58)
    at loadESM (node:internal/process/esm_loader:90:11)
Emitted 'error' event on Tinypool instance at:
    at EventEmitterReferencingAsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at Tinypool.emit (file:///C:/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/cache/tinypool-npm-0.3.0-e11f8ec8eb-92291c309e.zip/node_modules/tinypool/dist/esm/index.js:60:31)
    at Worker.<anonymous> (file:///C:/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/cache/tinypool-npm-0.3.0-e11f8ec8eb-92291c309e.zip/node_modules/tinypool/dist/esm/index.js:566:30)
    at Worker.emit (node:events:513:28)
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by atk** [comment]
Can you try that again using WSL? This looks like a Windows incompatibility of tinypool.

**Comment by JakeYallop** [comment]
Just given it a go on WSL (Ubuntu 20.04) - I ran yarn to reinstall the linux specific dependencies required by esbuild, and with the same configuration as above (`registerNodeLoader: true`), and I get the exact same error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/mnt/c/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/__virtual__/vitest-virtual-e7e43f7ad2/0/cache/vitest-npm-0.25.3-4ee5af907c-cd54de758f.zip/node_modules/vitest/dist/loader.js' imported from /mnt/c/Users/JakeYallop/source/repos/SolidjsTestingRepro/playground/
Did you mean to import /mnt/c/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/__virtual__/vitest-virtual-e7e43f7ad2/0/cache/vitest-npm-0.25.3-4ee5af907c-cd54de758f.zip/node_modules/vitest/dist/loader.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at initializeLoader (node:internal/process/esm_loader:74:49)
    at loadESM (node:internal/process/esm_loader:87:11)
    at runMainESM (node:internal/modules/run_main:47:21)
Emitted 'error' event on Tinypool instance at:
    at EventEmitterReferencingAsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at Tinypool.emit (file:///mnt/c/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/cache/tinypool-npm-0.3.0-e11f8ec8eb-92291c309e.zip/node_modules/tinypool/dist/esm/index.js:60:31)
    at Worker.<anonymous> (file:///mnt/c/Users/JakeYallop/source/repos/SolidjsTestingRepro/.yarn/cache/tinypool-npm-0.3.0-e11f8ec8eb-92291c309e.zip/node_modules/tinypool/dist/esm/index.js:566:30)
    at Worker.emit (node:events:390:28)
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I also tried with the inline option - same error as before (render is not a function).

**Comment by atk** [comment]
There's some "virtual" module in there that cannot be loaded for some reason. Did you `yarn link` any packages?

**Comment by JakeYallop** [comment]
Not explicitly - I do have yarn workspaces enabled (as shown in the repro repo), and I think that might do some sym linking in the background - although I have no workspace packages referenced in the repro repository.

**Comment by JakeYallop** [comment]
Had a thought - I gave it a run with `nodeLinker: node-modules` in the .yarnrc.yml file, which as far as I understand it, should just revert to old node modules behaviour. More info here: https://yarnpkg.com/getting-started/migration#if-required-enable-the-node-modules-plugin

This unfortunately did not work - I got a "render is not a function" with the inline deps version, and
```
The requested module 'solid-js/web' does not provide an export named 'hydrate'
```
with `registerNodeLoader: true`.

Not sure if this helps figure out the underlying issue at all. I was also poking around and found [some information about ESBuild and Plug'n'Play](https://yarnpkg.com/features/pnp#support-via-plugins) - which suggests there have been issues with ESBuild in the past, however, this seems to be fixed from version ESBuild v0.15, and the reproduction above is using ESBuild v0.15.15.
```
$ yarn workspace @solidjsrepro/playground info esbuild -R
└─ esbuild@npm:0.15.15
   ├─ Version: 0.15.15
   │
   ├─ Exported Binaries
   │  └─ esbuild
   │
   └─ Dependencies
      ├─ @esbuild/android-arm@npm:0.15.15 → npm:0.15.15  
      ├─ @esbuild/linux-loong64@npm:0.15.15 → npm:0.15.15
      ├─ esbuild-android-64@npm:0.15.15 → npm:0.15.15    
      ├─ esbuild-android-arm64@npm:0.15.15 → npm:0.15.15 
      ├─ esbuild-darwin-64@npm:0.15.15 → npm:0.15.15     
      ├─ esbuild-darwin-arm64@npm:0.15.15 → npm:0.15.15  
      ├─ esbuild-freebsd-64@npm:0.15.15 → npm:0.15.15    
      ├─ esbuild-freebsd-arm64@npm:0.15.15 → npm:0.15.15 
      ├─ esbuild-linux-32@npm:0.15.15 → npm:0.15.15      
      ├─ esbuild-linux-64@npm:0.15.15 → npm:0.15.15      
      ├─ esbuild-linux-arm64@npm:0.15.15 → npm:0.15.15   
      ├─ esbuild-linux-arm@npm:0.15.15 → npm:0.15.15     
      ├─ esbuild-linux-mips64le@npm:0.15.15 → npm:0.15.15
      ├─ esbuild-linux-ppc64le@npm:0.15.15 → npm:0.15.15 
      ├─ esbuild-linux-riscv64@npm:0.15.15 → npm:0.15.15 
      ├─ esbuild-linux-s390x@npm:0.15.15 → npm:0.15.15   
      ├─ esbuild-netbsd-64@npm:0.15.15 → npm:0.15.15     
      ├─ esbuild-openbsd-64@npm:0.15.15 → npm:0.15.15
      ├─ esbuild-sunos-64@npm:0.15.15 → npm:0.15.15
      ├─ esbuild-windows-32@npm:0.15.15 → npm:0.15.15
      ├─ esbuild-windows-64@npm:0.15.15 → npm:0.15.15
      └─ esbuild-windows-arm64@npm:0.15.15 → npm:0.15.15
```

**Comment by JakeYallop** [comment]
I've just given pnpm a go. You can reproduce the below using the https://github.com/JakeYallop/SolidjsRepro/tree/use-pnpm branch.

Unfortunately, I still run into the same errors as above - 
`registerNodeModules: true`
```
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'hydrate'
 ❯ src/App.test.tsx:5:31
      4| 
      5| describe("App", () => {
      6|   it("should render", () => {
       |       ^
      7|     render(() => <App />);
      8|   });
```

`inline`
```
TypeError: render is not a function
 ❯ Module.render ../node_modules/.pnpm/@solidjs+testing-library@0.5.1_solid-js@1.6.2/node_modules/@solidjs/testing-library/dist/index.js:29:105
     30|     container,
     31|     baseElement,
     32|     debug: (el = baseElement, maxLength, options2) => Array.isArray(el) ? el.forEach((e) => console.log(prettyDOM(e, maxLength, options2))) : console.log(prettyDOM(el, maxLength, options2)),
       |                             ^
     33|     unmount: dispose,
     34|     ...queryHelpers
```

```
pnpm --version
7.17.1
```

**Comment by atk** [comment]
Ah, you're missing the conditions: outside of test, add

```js
  resolve: {
    conditions: ['development', 'browser'],
  },
```

**Comment by JakeYallop** [comment]
That was it! Thanks for the help.

Yarn also works perfectly once those settings are added.

I'm a tad confused as to why those conditions are needed though - the documentation for [`resolve.conditions`](https://vitejs.dev/config/shared-options.html#resolve-conditions) specifies:
> Vite has a list of "allowed conditions" and will match the first condition that is in the allowed list. The default allowed conditions are: import, module, browser, default, and production/development based on current mode. The resolve.conditions config option allows specifying additional allowed conditions.

Which suggests that vite includes those allowed conditions as default.

With a bit of trial and error, it turns out that all I need is "browser" specified.

**Comment by JakeYallop** [comment]
In regards the above, we can see that the [package.json](https://github.com/solidjs/solid/blob/c993eb0c6fb7e39772759f1f7605fdb27dbf5863/packages/solid/package.json#L13-L14) for solidjs has the node conditional export first in the list, and I'm assuming that setting that condition changes the resolution order somehow.

Seems like this behaviour is by design, but definitely lead to a confusing set of circumstances in this case that was non-obvious to debug.
https://github.com/solidjs/solid/issues/1102#issuecomment-1175810439

Closing this issue as the original issue is resolved.

**Comment by atk** [comment]
Thank you for your patience and feedback.
